spring.application.name=apigetitem

spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.jpa.database-platform=org.hibernate.dialect.DB2Dialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=${DB_PORT}


#LE O ARQUIVO .ENV PARA CARREGAR AS VARIÁVEIS DE AMBIENTE
spring.config.import=optional:file:.env[.properties]
